services:
  db:
    image: postgres:latest
    restart: always
    container_name: smartcalc-postgres
    environment:
      POSTGRES_DB: calculator_db
      POSTGRES_USER: calc_user
      POSTGRES_PASSWORD: calc_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - smartcalc-network

volumes:
  postgres-data:

networks:
  smartcalc-network: